// src/lib/pushSubscription.js - Client-side Web Push Subscription & Token Manager
'use client';

const COLLECTIONS = {
  PUSH_SUBSCRIPTIONS: 'pushSubscriptions',
};

const VAPID_PUBLIC_KEY = process.env.NEXT_PUBLIC_VAPID_PUBLIC_KEY || 'BGSNkX5qMqEFiHER_vSCjmdKNYmoboaRl4vCbMZEkFvuiGsqGP4AWcaRvP0cW2q0Ag2902A-q-0hK2JImitRpvE';

/**
 * Convert URL-safe base64 string to Uint8Array for PushManager
 */
function urlBase64ToUint8Array(base64String) {
  const padding = '='.repeat((4 - (base64String.length % 4)) % 4);
  const base64 = (base64String + padding)
    .replace(/-/g, '+')
    .replace(/_/g, '/');

  const rawData = window.atob(base64);
  const outputArray = new Uint8Array(rawData.length);

  for (let i = 0; i < rawData.length; ++i) {
    outputArray[i] = rawData.charCodeAt(i);
  }
  return outputArray;
}

/**
 * Generate a safe, deterministic Firestore document ID from subscription endpoint
 */
function getSubscriptionDocId(endpoint) {
  try {
    const encoded = btoa(endpoint).replace(/[/+=]/g, '_');
    return `sub_${encoded.slice(-80)}`;
  } catch (e) {
    return `sub_${Date.now()}`;
  }
}

/**
 * Check browser push notification support & current permission status
 */
export async function getPushStatus() {
  if (
    typeof window === 'undefined' ||
    !('serviceWorker' in navigator) ||
    !('PushManager' in window) ||
    !('Notification' in window)
  ) {
    return { isSupported: false, permission: 'unsupported', isSubscribed: false };
  }

  const permission = Notification.permission;

  try {
    const reg = await navigator.serviceWorker.ready;
    const sub = await reg.pushManager.getSubscription();
    return {
      isSupported: true,
      permission,
      isSubscribed: !!sub,
      subscription: sub ? sub.toJSON() : null,
    };
  } catch (err) {
    console.warn('[Push] Error querying subscription:', err);
    return { isSupported: true, permission, isSubscribed: false };
  }
}

/**
 * Subscribe user to Web Push notifications.
 * MUST be called as a result of a direct user action (e.g. clicking "Enable Notifications").
 */
export async function subscribeUserToPush() {
  if (
    typeof window === 'undefined' ||
    !('serviceWorker' in navigator) ||
    !('PushManager' in window) ||
    !('Notification' in window)
  ) {
    return { success: false, error: 'Push notifications are not supported on this device/browser.' };
  }

  // 1. Request user permission
  let permission = Notification.permission;
  if (permission === 'default') {
    try {
      permission = await Notification.requestPermission();
    } catch (e) {
      console.warn('[Push] Permission prompt failed:', e);
      return { success: false, error: 'Permission request failed.' };
    }
  }

  if (permission !== 'granted') {
    return {
      success: false,
      permission,
      error: permission === 'denied'
        ? 'Notifications are blocked in your browser settings. Please enable notifications to subscribe.'
        : 'Notification permission was not granted.'
    };
  }

  try {
    // 2. Wait for Service Worker
    const reg = await navigator.serviceWorker.ready;

    // 3. Check for existing subscription or create new one
    let sub = await reg.pushManager.getSubscription();

    if (!sub) {
      const appServerKey = urlBase64ToUint8Array(VAPID_PUBLIC_KEY);
      sub = await reg.pushManager.subscribe({
        userVisibleOnly: true,
        applicationServerKey: appServerKey,
      });
    }

    const subJson = sub.toJSON();

    if (!subJson.endpoint || !subJson.keys?.p256dh || !subJson.keys?.auth) {
      throw new Error('Incomplete push subscription generated by browser.');
    }

    // 4. Save to Firestore `pushSubscriptions` collection with deduplication
    try {
      const { db } = await import('./firebase');
      if (db) {
        const { doc, setDoc, serverTimestamp } = await import('firebase/firestore');
        const docId = getSubscriptionDocId(subJson.endpoint);
        const subRef = doc(db, COLLECTIONS.PUSH_SUBSCRIPTIONS || 'pushSubscriptions', docId);

        await setDoc(subRef, {
          endpoint: subJson.endpoint,
          keys: {
            p256dh: subJson.keys.p256dh,
            auth: subJson.keys.auth,
          },
          userAgent: navigator.userAgent || 'Unknown',
          platform: navigator.platform || 'Unknown',
          language: navigator.language || 'en',
          active: true,
          updatedAt: serverTimestamp(),
          createdAt: serverTimestamp(),
        }, { merge: true });
      }
    } catch (fsErr) {
      console.warn('[Push] Firestore sync warning (local push still active):', fsErr);
    }

    return { success: true, subscription: subJson };
  } catch (err) {
    console.error('[Push] Subscription failed:', err);
    return { success: false, error: err.message || 'Failed to subscribe to push notifications.' };
  }
}

/**
 * Unsubscribe user from Web Push notifications
 */
export async function unsubscribeUserFromPush() {
  if (typeof window === 'undefined' || !('serviceWorker' in navigator)) {
    return { success: false };
  }

  try {
    const reg = await navigator.serviceWorker.ready;
    const sub = await reg.pushManager.getSubscription();

    if (sub) {
      const subJson = sub.toJSON();
      await sub.unsubscribe();

      if (subJson.endpoint) {
        try {
          const { db } = await import('./firebase');
          if (db) {
            const { doc, updateDoc, serverTimestamp } = await import('firebase/firestore');
            const docId = getSubscriptionDocId(subJson.endpoint);
            const subRef = doc(db, COLLECTIONS.PUSH_SUBSCRIPTIONS || 'pushSubscriptions', docId);
            await updateDoc(subRef, {
              active: false,
              updatedAt: serverTimestamp(),
            }).catch(() => {});
          }
        } catch (fsErr) {
          console.warn('[Push] Firestore unsubscribe sync warning:', fsErr);
        }
      }
    }

    return { success: true };
  } catch (err) {
    console.error('[Push] Unsubscribe error:', err);
    return { success: false, error: err.message };
  }
}
